#!/bin/sh

WFI=/usr/local/bin/wait-for-it.sh
echo "installing ${WFI}"
wget -q -O ${WFI} https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
chmod a+x ${WFI}


echo "installing overalls"
go get -u github.com/go-playground/overalls

echo "installing gomock"
go get -u github.com/golang/mock/gomock

echo "installing mockgen"
go get -u github.com/golang/mock/mockgen

echo "installing goware/statik"
go get -u github.com/goware/statik
