#!/bin/sh

set -eu
#set -eux # debugging

TAR_FLAGS=-xzmok

HOME_TMP="${C_HOME_DIR}/tmp"


mkdir -p "${HOME_TMP}"

NAME="${C_FLAVOUR}-server"
PKG_NAME="${NAME}-${C_VERSION}-${C_OS}-${C_ARCH}.tar.gz"
LOCAL_PATH="/build.d/${PKG_NAME}"
REMOTE_URL="${C_REMOTE_BASE_URL}/${PKG_NAME}"

# See if COPY in Dockerfile picked up any local dist files
# and use them instead of downloading the whole package
#
# Used mainly for debugging
if [ -f "${LOCAL_PATH}" ]; then
  echo "Local packages found:"
  ls -lsa ${LOCAL_PATH}
  tar ${TAR_FLAGS} -f "${LOCAL_PATH}" -C "${HOME_TMP}";
else
    echo "Downloading server from"
    echo "${REMOTE_URL}"
  curl --silent --location "${REMOTE_URL?}" | tar ${TAR_FLAGS} -C "${HOME_TMP}"
fi

mv "${HOME_TMP}/${NAME}/"* "${C_HOME_DIR}/"
rm -rf "${HOME_TMP}"

BIN="${C_HOME_DIR}/bin/${NAME}"

# Released packages have "<flavour>-server" named binaries
#
# we'll link them to simple "server" that can be used as entrypoint
ln -s "${BIN}" "${C_HOME_DIR}/bin/server"
setcap cap_net_bind_service=+ep "${BIN}"
