= Demo & production Docker image building scripts for Corteza

== Outputs

=== Docker images

server::
Backend server and HTTP REST API server: combines compose, messaging and system backends and their APIs.
This binaries can be ran as one monolithic service or separately to achieve microservice-like architecture.

webapp::
Frontend client applications (one, auth, admin, compose and messaging). Static files served by NginX web server.

corredor::
Automation server

aio::
All-In-One: combines server, webapp files, corredor automation server.

demo::
Combines server, webapp files, corredor and MySQL database server.

== Building images
[source]
----
make build.<output>
----

Note: VERSION will default to last tag on THIS repository!
You can set it to any value with make argument (VERSION=foo)

This VERSION argument is then used for docker image tagging AND
for downloading release package (this is done inside each output's Dockerfile)

Docker tag can be overriden by TAG argument


=== Examples

. Build monolith server from `unstable` release (`develop` branch) and tag docker image it with `unstable` tag.
[source,sh]
----
make build.server-monolith VERSION=unstable
----

. Build webapp from `2020.6` release (`2020.6` git tag) and tag docker image it with `latest` tag.
[source,sh]
----
make build.webpp VERSION=2020.6 TAG=latest
----
