= Demo & production Docker image building scripts for Corteza

== Outputs

=== Docker images

server::
Backend server and HTTP REST API server: combines compose and system backends and their APIs.

webapp::
Frontend client applications (one, admin, compose). Static files served by NginX web server.

corredor::
Automation server

== Building images

Build and push all images (from root)
[source]
----
make VERSION=2020.12.0
----

This will build server, webapp and corredor.

Each image can be built independently by changing into one of the directories and running `make`

== Release packages (binaries and bundles)

Most important thing to keep in mind is that package MUST released on https://releases.cortezaproject.org/files/.
This happens in the final step of the CI pipeline on each repository.

As an alternative you can place testing release package inside build.d/ where it's detected by image build scripts.

== Versions

Valid version formats:


`202<Y>-<release month>`::
    Will suffix with .0 patch. See next format.

`202<Y>-<release month>-<patch>`::
    Builds image with  `<year>-<release month>-<patch>` and `<year>-<release month>` tag.

`<arbitrary-string>`::
    Builds image with `<arbitrary-string>`

If `LATEST=yes` is set and non-arbitrary-string version is used, images are also tagged with `latest`


.Examples:
[source]
----
make VERSION=2020.12
make VERSION=unstable
make VERSION=2020.12.2 LATEST=yes
----


=== Version mix & match

Webapp and server images build supports version cascading (see `Makefile.inc` for details).

.Compiling specific feature build for server with base unstable version for webapp with exception of compose:
[source]
----
make VERSION=2020.12.x-feature-xyz VERSION_WEBAPP=unstable VERSION_WEBAPP_COMPOSE=2020.12.x-feature-xyz
----

This will build image with `2020.12.x-feature-xyz` tag with all but compose webapps on unstable version
