#!/bin/sh

set -eu
#set -eux # debugging

# Cairo&co are needed for PDF rendering
apk add --no-cache \
    ca-certificates \
    tzdata \
    git \
    build-base \
    g++ \
    cairo-dev \
    jpeg-dev \
    pango-dev \
    giflib-dev \
    curl \

rm -rf /tmp/*
